---
title: Pixel pet
hero_image: images/banner.png
description: Make a walking pixel pet with your Raspberry Pi and a Sense HAT
original_url: https://www.raspberrypi.org/learning/pixel-pet/
theme: red
duration: 2
ingredient: false
listed: false
copyedit: true
curriculum: 3, design-1, programming-3, phys-comp-1, manufacture-0, community-0
interests: animals, games
technologies: raspberry-pi, python, sense-hat
hardware: ''
software: ''
site_areas: projects
version: 4.0.1
last_tested: 2018-02-01
steps:
- title: Step 1
- title: Step 2
  completion:
  - engaged
- title: Step 3
- title: Step 4
- title: Step 5
- title: Step 6
- title: Step 7
- title: Step 8
  completion:
  - internal
  - external
